### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by DimonYoing** [KygekTeam/KygekPingTPS#10]
I have an error in the console

**Comment by DimonYoing** [comment]
![2022_02_11_18 28 20](https://user-images.githubusercontent.com/98219533/153599907-da01106f-cbeb-46b6-9602-e64f8365d53d.jpg)
![2022_02_11_18 28 24](https://user-images.githubusercontent.com/98219533/153599911-25b6ca42-a5d4-4e42-9b44-2ef420b33fc4.jpg)
![2022_02_11_18 28 29](https://user-images.githubusercontent.com/98219533/153599916-1746c7e4-a186-4b19-b6e1-70f7cf430488.jpg)

**Comment by KygekDev** [comment]
Probably because you didn't download from Poggit CI/Poggit Releases.

Download the latest KygekPingTPS here: https://poggit.pmmp.io/p/KygekPingTPS
