### ISSUE TITLE
Added Custom Prefix

### ISSUE THREAD

**Issue by ghost** [KygekTeam/KygekPingTPS#2]
Add Custom Prefix in All Kygek Plugin?

**Comment by KygekDev** [comment]
We might add this feature to all of our plugins.

KygekPingTPS will be the first plugin that implements this feature.

**Comment by NTT1906** [comment]
over a year latter....

**Comment by NhanAZ** [comment]
Over 2 years later

**Comment by ghost** [comment]
I just added it in version 2.0.1
