### ISSUE TITLE
If you download the file from github it won't load

### ISSUE THREAD

**Issue by UnEnanoMas** [KygekTeam/KygekPingTPS#3]
[CrashTPS.txt](https://github.com/KygekTeam/KygekPingTPS/files/6288591/CrashTPS.txt)

I manage better with folders than with .phar, and I tried to put KygekPingTPS in a folder and when I turned it on, that error would appear.

**Comment by KygekDev** [comment]
KygekPingTPS uses the UpdateNotifier virion. This means you must download the plugin on Poggit, unless you use DEVirion plugin and add UpdateNotifier virion.
